clothes_jxc/cmsys/urls.py
from django.contrib import admin
from django.urls import path, include

from common import views

app_name = 'customer'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('changpwd/', views.changepwd, name='changepwd'),
    path('captcha', include('captcha.urls')),
    path('user/', include('user.urls')),
    path('customer/', include('customer.urls')),
    path('clothes/', include('clothes.urls')),
    path('inorder/', include('inorder.urls')),
    path('outorder/', include('outorder.urls')),
    path('checkusername/<str:username>/',views.checkusername, name='checkusername')
]

clothes_jxc/customer/urls.py
from django.urls import path

from . import views

app_name = 'customer'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:customer_id>', views.update, name='update'),
    path('delete/<int:customer_id>', views.delete, name='delete')
]

clothes_jxc/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:user_id>', views.update, name='update'),
    path('delete/<int:user_id>', views.delete, name='delete')
]

clothes_jxc/customer/models.py
from django.db import models

# Create your models here.

clothes_jxc/customer/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError


def phone_validate(value):
    phone_re = re.compile(r'^1[3456789]\d{9}$')
    if not phone_re.match(value):
        raise ValidationError('手机格式错误')


class CustomerForm(forms.Form):
    id = forms.IntegerField(label='ID', required=False,
                            widget=forms.TextInput({'class': 'form-control', 'disabled': 'disabled'}))
    name = forms.CharField(label='客户名', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(label='电话', validators=[phone_validate, ], max_length=11,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label='地址', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    create_time = forms.CharField(label='创建时间', required=False, max_length=32,
                                  widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'}))

clothes_jxc/customer/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from common.models import Customer
from customer.forms import CustomerForm


def list(request):
    # 返回一个 QuerySet 对象 ，包含所有的表记录
    qs = Customer.objects.all()
    paginator = Paginator(qs, 10)
    page = request.GET.get('page', '1')
    result = paginator.page(page)
    context = {
        'result': result
    }
    return render(request, 'customer/index.html', context)


def add(request):
    if request.method == "POST":
        customer_form = CustomerForm(request.POST)
        if customer_form.is_valid():
            name = customer_form.cleaned_data['name']
            phone = customer_form.cleaned_data['phone']
            address = customer_form.cleaned_data['address']

            new_customer = Customer.objects.create(name=name,
                                                   phone=phone,
                                                   address=address)
            context = {
                'id': new_customer.id
            }
            messages.add_message(request, messages.WARNING, '添加成功')
            return redirect(reverse('customer:index'))

        else:
            context = {
                'customer_form': customer_form
            }
            messages.add_message(request, messages.WARNING, '请检查填写的内容')
            return render(request, 'customer/add.html', context)
    else:
        customer_form = CustomerForm()
        context = {
            'customer_form': customer_form
        }
        return render(request, 'customer/add.html', context)


def search(request):
    object = Customer.objects
    qs = object.values()
    id = request.POST.get('id')
    name = request.POST.get('name')
    phone = request.POST.get('phone')
    address = request.POST.get('address')
    if id:
        qs = object.filter(id=id)
    if name:
        qs = object.filter(name=name)
    if phone:
        qs = object.filter(phone=phone)
    if address:
        qs = object.filter(address__contains=address)
    paginator = Paginator(qs, 10)
    page = request.GET.get('page', '1')
    result = paginator.page(page)
    context = {
        'result': result
    }
    messages.add_message(request, messages.SUCCESS, '查询成功')
    return render(request, 'customer/index.html', context)


def update(request, customer_id):
    customer = Customer.objects.get(id=customer_id)

    if request.method == "POST":
        customer_form = CustomerForm(request.POST)
        if customer_form.is_valid():
            name = customer_form.cleaned_data['name']
            phone = customer_form.cleaned_data['phone']
            address = customer_form.cleaned_data['address']

            if name:
                customer.name = name
            if phone:
                customer.phone = phone
            if address:
                customer.address = address

            customer.save()
            context = {
                'customer_id': customer_id
            }
            messages.add_message(request, messages.SUCCESS, '修改成功')
            return redirect(reverse('customer:index'))
        else:
            context = {
                'customer_form': customer_form
            }
            messages.add_message(request, messages.WARNING, '请检查填写的内容')
            return render(request, 'customer/edit.html', context)
    else:
        customer_form = CustomerForm({'id': customer.id,
                                      'name': customer.name,
                                      'phone': customer.phone,
                                      'address': customer.address,
                                      'create_time': customer.create_time})
        context = {
            'customer_form': customer_form,
            'customer_id': customer_id
        }
        return render(request, 'customer/edit.html', context)


def delete(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    customer.delete()
    messages.add_message(request, messages.SUCCESS, '删除成功')
    return redirect(reverse('customer:index'))

clothes_jxc/customer/templates/customer/add.html
{% extends 'base.html' %}
{% block title %}添加客户{% endblock %}
{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-customer' action="{% url 'customer:add' %}" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">添加客户</h2>
                <div class="form-group">
                    {{ customer_form.name.label_tag }}
                    {{ customer_form.name }}
                    {{ customer_form.name.errors }}

                </div>
                <div class="form-group">
                    {{ customer_form.phone.label_tag }}
                    {{ customer_form.phone }}
                    {{ customer_form.phone.errors }}
                </div>
                <div class="form-group">
                    {{ customer_form.address.label_tag }}
                    {{ customer_form.address }}
                    {{ customer_form.address.errors }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">添加</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/customer/templates/customer/edit.html
{% extends 'base.html' %}
{% block title %}修改客户{% endblock %}
{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-user' action="{% url 'customer:update' customer_id %}" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">修改客户</h2>
                <div class="form-group">
                    {{ customer_form.id.label_tag }}
                    {{ customer_form.id }}
                    {{ customer_form.id.errors }}
                </div>
                <div class="form-group">
                    {{ customer_form.name.label_tag }}
                    {{ customer_form.name }}
                    {{ customer_form.name.errors }}
                </div>
                <div class="form-group">
                    {{ customer_form.phone.label_tag }}
                    {{ customer_form.phone }}
                    {{ customer_form.phone.errors }}
                </div>
                <div class="form-group">
                    {{ customer_form.address.label_tag }}
                    {{ customer_form.address }}
                    {{ customer_form.address.errors }}
                </div>
                <div class="form-group">
                    {{ customer_form.create_time.label_tag }}
                    {{ customer_form.create_time }}
                    {{ customer_form.create_time.errors }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">保存</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/customer/templates/customer/index.html
{% extends 'base.html' %}
{% block title %}客户管理{% endblock %}
{% block content %}
    <div id="content" style="height: 600px">
        <div id="search" class="text-center">
            <form class="form-inline" action="{% url 'customer:search' %} " method="post">
                <div class="form-group ">
                    <a class="btn btn-info" href="{% url 'customer:add' %}">添加</a>
                </div>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" placeholder="输入ID查询">
                </div>
                <div class="form-group">
                    <label for="name">客户名</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="输入客户名查询">
                </div>
                <div class="form-group">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="输入电话查询">
                </div>
                <div class="form-group">
                    <label for="address">地址</label>
                    <input type="text" class="form-control" id="address" name="address" placeholder="输入电话查询">
                </div>
                <button type="submit" class="btn btn-success">查询</button>
            </form>
        </div>
        <br>
        <div id="table" align="center">
            {% if result %}
                <table class="table table-striped table-bordered table-hover  table-condensed" style="width: 1100px">
                <tr class="success">
                    <td>ID</td>
                    <td>客户名</td>
                    <td>电话</td>
                    <td>地址</td>
                    <td>创建时间</td>
                    <td>修改时间</td>
                    <td>编辑</td>
                    <td>删除</td>
                </tr>
                {% for foo in result %}
                    <tr>
                        <td>{{ foo.id }}</td>
                        <td>{{ foo.name }}</td>
                        <td>{{ foo.phone }}</td>
                        <td>{{ foo.address }}</td>
                        <td>{{ foo.create_time }}</td>
                        <td>{{ foo.modify_time }}</td>
                        <td><a class="btn btn-primary btn-sm" href="{% url 'customer:update' foo.id %}">编辑</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'customer:delete' foo.id %}">删除</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>没有任何客户</p>
            {% endif %}
            </table>
        </div>
        <!-- 分页开始 -->
        <div class="text-center">
            <ul class="pagination">
                <li><a href="/customer/?page=1" rel="external nofollow">首页</a></li>
                {% if result.has_previous %}
                    <li><a href="/customer/?page={{ result.previous_page_number }}" rel="external nofollow">上一页</a></li>
                {% endif %}
                {% for num in result.paginator.page_range %}
                    <li><a href="/customer/?page={{ num }}" rel="external nofollow">{{ num }}</a></li>
                {% endfor %}
                {% if result.has_next %}
                    <li><a href="/customer/?page={{ result.next_page_number }}" rel="external nofollow">下一页</a></li>
                {% endif %}
                <li><a href="/customer/?page={{ result.paginator.num_pages }}" rel="external nofollow">尾页</a></li>
            </ul>
        </div>
    <!-- 分页结束 -->
    </div>
{% endblock %}