clothes_jxc/clothes/urls.py
from django.urls import path

from . import views

app_name = 'clothes'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:clothes_id>', views.update, name='update'),
    path('delete/<int:clothes_id>', views.delete, name='delete'),
    path('checkstock/<int:clothes_id>', views.checkstock, name='checkstock')
]

clothes_jxc/cmsys/urls.py
from django.contrib import admin
from django.urls import path, include

from common import views

app_name = 'customer'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('changpwd/', views.changepwd, name='changepwd'),
    path('captcha', include('captcha.urls')),
    path('user/', include('user.urls')),
    path('customer/', include('customer.urls')),
    path('clothes/', include('clothes.urls')),
    path('inorder/', include('inorder.urls')),
    path('outorder/', include('outorder.urls')),
    path('checkusername/<str:username>/',views.checkusername, name='checkusername')
]

clothes_jxc/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:user_id>', views.update, name='update'),
    path('delete/<int:user_id>', views.delete, name='delete')
]

clothes_jxc/clothes/models.py
from django.db import models

# Create your models here.

clothes_jxc/clothes/forms.py
from django import forms


class ClothesForm(forms.Form):
    size_choices = (
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL')
    )
    id = forms.IntegerField(label='ID', required=False,
                            widget=forms.TextInput({'class': 'form-control', 'disabled': 'disabled'}))
    name = forms.CharField(label='服装名', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    sn = forms.CharField(label='服装号', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    price = forms.DecimalField(label='价格', max_digits=10, decimal_places=2,
                               widget=forms.NumberInput(attrs={'class': 'form-control'}))
    size = forms.ChoiceField(label='尺寸', choices=size_choices, widget=forms.Select(attrs={'class': 'form-control'}))
    color = forms.CharField(label='颜色', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    stock = forms.IntegerField(label='库存', widget=forms.NumberInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(label='图片', required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    desc = forms.CharField(label='描述', required=False, max_length=200,
                           widget=forms.Textarea(attrs={'class': 'form-control'}))

clothes_jxc/clothes/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse

from clothes.forms import ClothesForm
from common.models import Clothes


def list(request):
    # 返回一个 QuerySet 对象 ，包含所有的表记录
    qs = Clothes.objects.all()
    short = []
    for foo in qs:
        if foo.stock < 10:
            short.append(foo.name)
    short_str = '、'.join(short)
    messages.add_message(request, messages.WARNING, f'{str(short_str)}库存不足')
    paginator = Paginator(qs, 10)
    page = request.GET.get('page', '1')
    result = paginator.page(page)
    context = {
        'result': result,
    }
    return render(request, 'clothes/index.html', context)


def add(request):
    if request.method == "POST":
        clothes_form = ClothesForm(request.POST)
        if clothes_form.is_valid():
            name = clothes_form.cleaned_data['name']
            sn = clothes_form.cleaned_data['sn']
            price = clothes_form.cleaned_data['price']
            size = clothes_form.cleaned_data['size']
            color = clothes_form.cleaned_data['color']
            stock = clothes_form.cleaned_data['stock']
            desc = clothes_form.cleaned_data['desc']

            new_clothes = Clothes.objects.create(name=name,
                                                 sn=sn,
                                                 price=price,
                                                 size=size,
                                                 color=color,
                                                 stock=stock,
                                                 desc=desc)
            context = {
                'id': new_clothes.id,
            }
            messages.add_message(request, messages.SUCCESS, '添加成功')
            return redirect('/clothes/')

        else:
            context = {
                'clothes_form': clothes_form
            }
            messages.add_message(request, messages.WARNING, '请检查填写的内容')
            return render(request, 'clothes/add.html', context)
    else:
        clothes_form = ClothesForm()
        context = {
            'clothes_form': clothes_form
        }
        return render(request, 'clothes/add.html', context)


def search(request):
    object = Clothes.objects
    qs = object.values()
    id = request.POST.get('id')
    name = request.POST.get('name')
    sn = request.POST.get('sn')
    min = request.POST.get('min')
    max = request.POST.get('max')
    size = request.POST.get('size')
    color = request.POST.get('color')
    if id:
        qs = object.filter(id=id)
    if name:
        qs = object.filter(name=name)
    if sn:
        qs = object.filter(sn=sn)
    if min:
        qs = object.filter(price__gte=min)
    if max:
        qs = object.filter(price__lte=max)
    if size:
        qs = object.filter(size=size)
    if color:
        qs = object.filter(color=color)
    paginator = Paginator(qs, 10)
    page = request.GET.get('page', '1')
    result = paginator.page(page)
    context = {
        'result': result
    }
    messages.add_message(request, messages.SUCCESS, '查询成功')
    return render(request, 'clothes/index.html', context)


def update(request, clothes_id):
    clothes = Clothes.objects.get(id=clothes_id)

    if request.method == "POST":
        clothes_form = ClothesForm(request.POST)
        if clothes_form.is_valid():
            name = clothes_form.cleaned_data['name']
            sn = clothes_form.cleaned_data['sn']
            price = clothes_form.cleaned_data['price']
            size = clothes_form.cleaned_data['size']
            color = clothes_form.cleaned_data['color']
            stock = clothes_form.cleaned_data['stock']
            desc = clothes_form.cleaned_data['desc']

            if name:
                clothes.name = name
            if sn:
                clothes.sn = sn
            if price:
                clothes.price = price
            if size:
                clothes.size = size
            if color:
                clothes.color = color
            if stock:
                clothes.stock = stock
            if desc:
                clothes.desc = desc

            clothes.save()

            context = {
                'clothes_id': clothes_id
            }
            messages.add_message(request, messages.SUCCESS, '修改成功')
            return redirect(reverse('clothes:index'))
        else:
            context = {
                'clothes_form': clothes_form
            }
            messages.add_message(request, messages.WARNING, '请检查填写的内容')
            return render(request, 'clothes/edit.html', context)
    else:
        clothes_form = ClothesForm({'id': clothes.id,
                                    'name': clothes.name,
                                    'sn': clothes.sn,
                                    'price': clothes.price,
                                    'size': clothes.size,
                                    'color': clothes.color,
                                    'stock': clothes.stock,
                                    'desc': clothes.desc})
        context = {
            'clothes_form': clothes_form,
            'clothes_id': clothes_id
        }
        return render(request, 'clothes/edit.html', context)


def delete(request, clothes_id):
    clothes = Clothes.objects.get(id=clothes_id)
    clothes.delete()
    messages.add_message(request, messages.SUCCESS, '删除成功')
    return redirect(reverse('clothes:index'))


def checkstock(request, clothes_id):
    clothes = Clothes.objects.get(id=clothes_id)
    return JsonResponse({'stock': clothes.stock})

clothes_jxc/clothes/templates/clothes/edit.html
{% extends 'base.html' %}
{% block title %}用户服装{% endblock %}
{% block content %}
    <div class="container" style="height: auto">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-user' action="{% url 'clothes:update' clothes_id %}" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">修改服装</h2>
                <div class="form-group">
                    {{ clothes_form.id.label_tag }}
                    {{ clothes_form.id }}
                    {{ clothes_form.id.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.name.label_tag }}
                    {{ clothes_form.name }}
                    {{ clothes_form.name.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.sn.label_tag }}
                    {{ clothes_form.sn }}
                    {{ clothes_form.sn.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.price.label_tag }}
                    {{ clothes_form.price }}
                    {{ clothes_form.price.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.size.label_tag }}
                    {{ clothes_form.size }}
                    {{ clothes_form.size.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.color.label_tag }}
                    {{ clothes_form.color }}
                    {{ clothes_form.color.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.stock.label_tag }}
                    {{ clothes_form.stock }}
                    {{ clothes_form.stock.errors }}
                </div>
                <div class="form-group">
                    {{ clothes_form.desc.label_tag }}
                    {{ clothes_form.desc }}
                    {{ clothes_form.desc.errors }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">保存</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/clothes/templates/clothes/index.html
{% extends 'base.html' %}
{% block title %}服装管理{% endblock %}
{% block content %}
    <div id="content" style="height: 600px">
        <div id="search" class="text-center">
            <form class="form-inline" action="{% url 'clothes:search' %} " method="post">
                <div class="form-group ">
                    <a class="btn btn-info" href="{% url 'clothes:add' %}">添加</a>
                </div>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" placeholder="输入ID查询" style="width: 100px">
                </div>
                <div class="form-group">
                    <label for="name">服装名</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="输入服装名查询"
                           style="width: 110px">
                </div>
                <div class="form-group">
                    <label for="sn">服装编号</label>
                    <input type="text" class="form-control" id="sn" name="sn" placeholder="输入服装编号查询"
                           style="width: 110px">
                </div>
                <div class="form-group">
                    <label for="price">价格</label>
                    <input type="text" class="form-control" id="min" name="min" placeholder="最小价格" style="width: 100px">--
                    <input type="text" class="form-control" id="max" name="max" placeholder="最大价格" style="width: 100px">
                </div>
                <div class="form-group">
                    <label for="size">尺寸</label>
                    <select id="size" name="size" class="form-control">
                        <option style='display: none'></option>
                        <option>S</option>
                        <option>M</option>
                        <option>L</option>
                        <option>XL</option>
                        <option>XXL</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="color">颜色</label>
                    <input type="text" class="form-control" id="color" name="color" placeholder="输入颜色查询"
                           style="width: 110px">
                </div>
                <button type="submit" class="btn btn-success">查询</button>
            </form>
        </div>
        <br>
        <div id="table" align="center">
            {% if result %}
                <table class="table table-striped table-bordered table-hover  table-condensed" style="width: 1100px">
                <tr class="success">
                    <td>ID</td>
                    <td>服装名</td>
                    <td>服装号</td>
                    <td>价格</td>
                    <td>尺寸</td>
                    <td>颜色</td>
                    <td>库存</td>
                    <td>描述</td>
                    <td>创建时间</td>
                    <td>修改时间</td>
                    <td>编辑</td>
                    <td>删除</td>
                </tr>
                {% for foo in result %}
                    <tr>
                        <td>{{ foo.id }}</td>
                        <td>{{ foo.name }}</td>
                        <td>{{ foo.sn }}</td>
                        <td>{{ foo.price }}</td>
                        <td>{{ foo.size }}</td>
                        <td>{{ foo.color }}</td>
                        {% if foo.stock > 10 %}
                            <td style="color: green">{{ foo.stock }}</td>
                        {% else %}
                            <td class="danger" style="color: red">{{ foo.stock }}</td>
                        {% endif %}
                        <td>{{ foo.desc }}</td>
                        <td>{{ foo.create_time }}</td>
                        <td>{{ foo.modify_time }}</td>
                        <td><a class="btn btn-primary btn-sm" href="{% url 'clothes:update' foo.id %}">编辑</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'clothes:delete' foo.id %}">删除</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>没有任何服装</p>
            {% endif %}
            </table>
        </div>
        <div class="text-center">
            <ul class="pagination">
                <li><a href="/clothes/?page=1" rel="external nofollow">首页</a></li>
                {% if result.has_previous %}
                    <li><a href="/clothes/?page={{ result.previous_page_number }}" rel="external nofollow">上一页</a></li>
                {% endif %}
                {% for num in result.paginator.page_range %}
                    <li><a href="/clothes/?page={{ num }}" rel="external nofollow">{{ num }}</a></li>
                {% endfor %}
                {% if result.has_next %}
                    <li><a href="/clothes/?page={{ result.next_page_number }}" rel="external nofollow">下一页</a></li>
                {% endif %}
                <li><a href="/clothes/?page={{ result.paginator.num_pages }}" rel="external nofollow">尾页</a></li>
            </ul>
        </div>
        <!-- 分页结束 -->
    </div>
{% endblock %}