clothes_jxc/cmsys/urls.py
from django.contrib import admin
from django.urls import path, include

from common import views

app_name = 'customer'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('changpwd/', views.changepwd, name='changepwd'),
    path('captcha', include('captcha.urls')),
    path('user/', include('user.urls')),
    path('customer/', include('customer.urls')),
    path('clothes/', include('clothes.urls')),
    path('inorder/', include('inorder.urls')),
    path('outorder/', include('outorder.urls')),
    path('checkusername/<str:username>/',views.checkusername, name='checkusername')
]

clothes_jxc/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:user_id>', views.update, name='update'),
    path('delete/<int:user_id>', views.delete, name='delete')
]

clothes_jxc/user/models.py
from django.db import models

# Create your models here.

clothes_jxc/user/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError


def username_validate(value):
    username_re = re.compile(r'^[a-zA-Z0-9]{4,16}$')
    if not username_re.match(value):
        raise ValidationError('用户名格式错误,只能输入4-16个字母、数字')


def password_validate(value):
    password_re = re.compile(r'^(a-zA-Z0-9){6,16}$')
    if not password_re.match(value):
        raise ValidationError('密码格式错误，只能输入6-20个字母、数字')


class UserForm(forms.Form):
    role_choices = (
        ('操作员', '操作员'),
        ('管理员', '管理员')
    )
    id = forms.IntegerField(label='ID', required=False,
                            widget=forms.TextInput({'class': 'form-control', 'disabled': 'disabled'}))
    username = forms.CharField(label="用户名", validators=[username_validate, ], max_length=32,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    name = forms.CharField(label="姓名", max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    role = forms.ChoiceField(label="角色", choices=role_choices, widget=forms.Select(attrs={'class': 'form-control'}))
    create_time = forms.CharField(label='创建时间', required=False, max_length=32,
                                  widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'}))

clothes_jxc/user/views.py
import hashlib

from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, reverse

# Create your views here.
from common.models import User
from user.forms import UserForm


def list(request):
    # 返回一个 QuerySet 对象 ，包含所有的表记录
    qs = User.objects.values()
    paginator = Paginator(qs, 10)
    page = request.GET.get('page', '1')
    result = paginator.page(page)
    context = {
        'result': result,
    }
    return render(request, 'user/index.html', context)


def add(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']
            name = user_form.cleaned_data['name']
            role = user_form.cleaned_data['role']

            new_user = User.objects.create(username=username,
                                           password=hash_code(password),
                                           name=name,
                                           role=role)
            context = {
                'id': new_user.id
            }
            messages.add_message(request, messages.SUCCESS, '添加成功')
            return redirect(reverse('user:index'))
        else:
            context = {
                'user_form': user_form
            }
            messages.add_message(request, messages.WARNING, '请检查填写的内容')
            return render(request, 'user/add.html', {'user_form': user_form})
    else:
        user_form = UserForm()
        context = {
            'user_form': user_form
        }
    return render(request, 'user/add.html', context)


def search(request):
    object = User.objects
    qs = object.values()
    id = request.POST.get('id')
    username = request.POST.get('username')
    name = request.POST.get('name')
    role = request.POST.get('role')
    if id:
        qs = object.filter(id=id)
    if username:
        qs = object.filter(username=username)
    if name:
        qs = object.filter(name=name)
    if role:
        qs = object.filter(role=role)
    paginator = Paginator(qs, 10)
    page = request.GET.get('page', '1')
    result = paginator.page(page)
    context = {
        'result': result
    }
    messages.add_message(request, messages.SUCCESS, '查询成功')
    return render(request, 'user/index.html', context)


def update(request, user_id):
    user = User.objects.get(id=user_id)

    if request.method == "POST":
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']
            name = user_form.cleaned_data['name']
            role = user_form.cleaned_data['role']

            if username:
                user.username = username
            print(password==user.password)
            if password == user.password:
                user.password = password
            else:
                user.password = hash_code(password)
            if name:
                user.name = name
            if role:
                user.role = role

            user.save()
            context = {
                'user_id': user_id
            }
            messages.add_message(request, messages.SUCCESS, '修改成功')
            return redirect(reverse('user:index'))
        else:
            context = {
                'user_form': user_form
            }
            messages.add_message(request, messages.WARNING, '请检查填写的内容')
            return render(request, 'user/edit.html', context)
    else:
        user_form = UserForm({'id': user.id,
                              'username': user.username,
                              'password': user.password,
                              'name': user.name,
                              'role': user.role,
                              'create_time': user.create_time})
        context = {
            'user_form': user_form,
            'user_id': user_id
        }
    return render(request, 'user/edit.html', context)


def delete(request, user_id):
    user = User.objects.get(id=user_id)
    user.delete()
    messages.add_message(request, messages.SUCCESS, '删除成功')
    return redirect(reverse('user:index'))


def hash_code(s, salt='psf'):  # 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接受bytes类型
    return h.hexdigest()

clothes_jxc/user/templates/user/add.html
{% extends 'base1.html' %}
{% block title %}添加用户{% endblock %}
{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-user' action="{% url 'user:add' %}" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">添加用户</h2>
                <div class="form-group">
                    {{ user_form.username.label_tag }}
                    {{ user_form.username }}
                    {{ user_form.username.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.password.label_tag }}
                    {{ user_form.password }}
                    {{ user_form.password.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.name.label_tag }}
                    {{ user_form.name }}
                    {{ user_form.name.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.role.label_tag }}
                    {{ user_form.role }}
                    {{ user_form.role.errors }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">添加</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/user/templates/user/edit.html
{% extends 'base1.html' %}
{% block title %}编辑用户{% endblock %}
{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-user' action="{% url 'user:update' user_id %}" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">修改用户</h2>
                <div class="form-group">
                    {{ user_form.id.label_tag }}
                    {{ user_form.id }}
                    {{ user_form.id.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.username.label_tag }}
                    {{ user_form.username }}
                    {{ user_form.username.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.password.label_tag }}
                    {{ user_form.password }}
                    {{ user_form.password.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.name.label_tag }}
                    {{ user_form.name }}
                    {{ user_form.name.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.role.label_tag }}
                    {{ user_form.role }}
                    {{ user_form.role.errors }}
                </div>
                <div class="form-group">
                    {{ user_form.create_time.label_tag }}
                    {{ user_form.create_time }}
                    {{ user_form.create_time.errors }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">保存</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/user/templates/user/index.html
{% extends 'base1.html' %}
{% block title %}用户管理{% endblock %}
{% block content %}
    <div id="content" style="height: 600px">
        <div id="search" class="text-center">
            <form class="form-inline" action="{% url 'user:search' %} " method="post">
                <div class="form-group ">
                    <a class="btn btn-info" href="{% url 'user:add' %}">添加</a>
                </div>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" placeholder="输入ID查询">
                </div>
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="输入用户名查询">
                </div>
                <div class="form-group">
                    <label for="name">姓名</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="输入姓名查询">
                </div>
                <div class="form-group">
                    <label for="role">角色</label>
                    <select id="role" name="role" class="form-control" style="width: 200px">
                        <option style='display: none'></option>
                        <option>管理员</option>
                        <option>操作员</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-success">查询</button>
            </form>
        </div>
        <br>
        <div id="table" align="center">
            {% if result %}
                <table class="table table-striped table-bordered table-hover  table-condensed" style="width: 1100px">
                <tr class="success">
                    <td>ID</td>
                    <td>用户名</td>
                    <td>密码</td>
                    <td>姓名</td>
                    <td>角色</td>
                    <td>创建时间</td>
                    <td>修改时间</td>
                    <td>编辑</td>
                    <td>删除</td>
                </tr>
                {% for foo in result %}
                    <tr>
                        <td>{{ foo.id }}</td>
                        <td>{{ foo.username }}</td>
                        <td>{{ foo.password }}</td>
                        <td>{{ foo.name }}</td>
                        <td>{{ foo.role }}</td>
                        <td>{{ foo.create_time }}</td>
                        <td>{{ foo.modify_time }}</td>
                        <td><a class="btn btn-primary btn-sm" href="{% url 'user:update' foo.id %}">编辑</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'user:delete' foo.id %}">删除</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>没有任何用户</p>
            {% endif %}
            </table>
        </div>
        <!-- 分页开始 -->
        <div class="text-center">
            <ul class="pagination">
                <li><a href="/user/?page=1" rel="external nofollow">首页</a></li>
                {% if result.has_previous %}
                    <li><a href="/user/?page={{ result.previous_page_number }}" rel="external nofollow">上一页</a></li>
                {% endif %}
                {% for num in result.paginator.page_range %}
                    <li><a href="/user/?page={{ num }}" rel="external nofollow">{{ num }}</a></li>
                {% endfor %}
                {% if result.has_next %}
                    <li><a href="/user/?page={{ result.next_page_number }}" rel="external nofollow">下一页</a></li>
                {% endif %}
                <li><a href="/user/?page={{ result.paginator.num_pages }}" rel="external nofollow">尾页</a></li>
            </ul>
        </div>
        <!-- 分页结束 -->
    </div>
{% endblock %}