clothes_jxc/clothes/urls.py
from django.urls import path

from . import views

app_name = 'clothes'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:clothes_id>', views.update, name='update'),
    path('delete/<int:clothes_id>', views.delete, name='delete'),
    path('checkstock/<int:clothes_id>', views.checkstock, name='checkstock')
]

clothes_jxc/cmsys/urls.py
from django.contrib import admin
from django.urls import path, include

from common import views

app_name = 'customer'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('changpwd/', views.changepwd, name='changepwd'),
    path('captcha', include('captcha.urls')),
    path('user/', include('user.urls')),
    path('customer/', include('customer.urls')),
    path('clothes/', include('clothes.urls')),
    path('inorder/', include('inorder.urls')),
    path('outorder/', include('outorder.urls')),
    path('checkusername/<str:username>/',views.checkusername, name='checkusername')
]

clothes_jxc/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.list, name='index'),
    path('add', views.add, name='add'),
    path('search', views.search, name='search'),
    path('update/<int:user_id>', views.update, name='update'),
    path('delete/<int:user_id>', views.delete, name='delete')
]

clothes_jxc/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">服装库存管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav faq-tabbable">
                <li class="active"><a href="{% url 'index' %}">主页</a></li>
                <li><a href="{% url 'user:index' %}">用户管理</a></li>
                <li><a href="{% url 'customer:index' %}">客户管理</a></li>
                <li><a href="{% url 'clothes:index' %}">服装管理</a></li>
                <li><a href="{% url 'inorder:index' %}">入库单管理</a></li>
                <li><a href="{% url 'outorder:index' %}">出库单管理</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="#">{{ request.session.user_role }}：{{ request.session.user_name }}</a></li>
                    <li><a href="{% url 'changepwd' %}">修改密码</a></li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% if request.session.is_login %}
    {% if messages %}
        <div id="messages" class="text-center">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <strong>信息提示：</strong> {{ message }}.
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% block content %}{% endblock %}
{% else %}
    {% if messages %}
        <div id="messages" class="text-center" style="display: none">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <strong>信息提示：</strong> {{ message }}.
                </div>
            {% endfor %}
        </div>
        {% endif %}
    <div class="container text-center" style="height: 600px">
        <h1>你尚未登录，只能访问公开内容！</h1>
    </div>
{% endif %}

<footer class="panel-footer">
    <p class="text-center">2019 © All Rights Reserved</p>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
<script src="{% static 'js/main.js' %}"></script>
</html>

clothes_jxc/templates/base1.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">服装库存管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav faq-tabbable">
                <li class="active"><a href="{% url 'index' %}">主页</a></li>
                <li><a href="{% url 'user:index' %}">用户管理</a></li>
                <li><a href="{% url 'customer:index' %}">客户管理</a></li>
                <li><a href="{% url 'clothes:index' %}">服装管理</a></li>
                <li><a href="{% url 'inorder:index' %}">入库单管理</a></li>
                <li><a href="{% url 'outorder:index' %}">出库单管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="#">{{ request.session.user_role }}：{{ request.session.user_name }}</a></li>
                    <li><a href="{% url 'changepwd' %}">修改密码</a></li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% if request.session.is_login %}
    {% if request.session.user_role == '管理员' %}
        {% if messages %}
            <div id="messages" class="text-center">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        <strong>信息提示：</strong> {{ message }}.
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        {% block content %}{% endblock %}
    {% else %}
        <div class="container text-center" style="height: 600px">
            <h1>你不是管理员，不能访问本页面的内容！</h1>
        </div>
    {% endif %}
{% else %}
    <div class="container text-center" style="height: 600px">
        <h1>你尚未登录，只能访问公开内容！</h1>
    </div>
{% endif %}

<footer class="panel-footer">
    <p class="text-center">2019 © All Rights Reserved</p>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
<script src="{% static 'js/main.js' %}"></script>
</html>

clothes_jxc/templates/base2.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">服装库存管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav faq-tabbable">
                <li class="active"><a href="{% url 'index' %}">主页</a></li>
                <li><a href="{% url 'user:index' %}">用户管理</a></li>
                <li><a href="{% url 'customer:index' %}">客户管理</a></li>
                <li><a href="{% url 'clothes:index' %}">服装管理</a></li>
                <li><a href="{% url 'inorder:index' %}">入库单管理</a></li>
                <li><a href="{% url 'outorder:index' %}">出库单管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="#">{{ request.session.user_role }}：{{ request.session.user_name }}</a></li>
                    <li><a href="{% url 'changepwd' %}">修改密码</a></li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% if messages %}
    <div id="messages" class="text-center">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <strong>信息提示：</strong> {{ message }}.
            </div>
        {% endfor %}
    </div>
{% endif %}
{% block content %}{% endblock %}

<footer class="panel-footer">
    <p class="text-center">2019 © All Rights Reserved</p>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
<script src="{% static 'js/main.js' %}"></script>
</html>

clothes_jxc/templates/changepwd.html
{% extends 'base.html' %}
{% block title %}修改客户{% endblock %}
{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-user' action="{% url 'changepwd' %}" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">修改密码</h2>
                <div class="form-group">
                    {{ changepwd_form.password_now.label_tag }}
                    {{ changepwd_form.password_now }}
                    {{ changepwd_form.password_now.errors }}
                </div>
                <div class="form-group">
                    {{ changepwd_form.password1.label_tag }}
                    {{ changepwd_form.password1 }}
                    {{ changepwd_form.password1.errors }}
                </div>
                <div class="form-group">
                    {{ changepwd_form.password2.label_tag }}
                    {{ changepwd_form.password2 }}
                    {{ changepwd_form.password2.errors }}
                </div>
                <div class="form-group">
                    {{ changepwd_form.captcha.label_tag }}
                    {{ changepwd_form.captcha }}
                    {{ changepwd_form.captcha.errors }}

                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">保存</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/templates/index.html
{% extends 'base2.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    <div class="container text-center" style="height: 600px">
        {% if request.session.is_login %}
            <h1>你好,{{ request.session.user_role }}：{{ request.session.user_name }}！欢迎回来！</h1>
            <p>以下是你你可操作的菜单</p>
                <div class="row center-block" style="width: 600px">
                    <div class="list-group col-xs-4 " style="width: 200px">
                        <a href="#" class="list-group-item active">系统管理</a>
                        {% if request.session.user_role == '管理员' %}
                            <a href="{% url 'user:index' %}" class="list-group-item">用户管理</a>
                        {% endif %}
                        <a href="{% url 'customer:index' %}" class="list-group-item">客户管理</a>
                        <a href="{% url 'clothes:index' %}" class="list-group-item">服装管理</a>
                    </div>
                    <div class="list-group col-xs-4" style="width: 200px">
                        <a href="#" class="list-group-item active">库存管理</a>
                        <a href="{% url 'inorder:index' %}" class="list-group-item">入库单管理</a>
                        <a href="{% url 'outorder:index' %}" class="list-group-item">出库单管理</a>
                    </div>
                    <div class="list-group col-xs-4" style="width: 200px">
                        <a href="#" class="list-group-item active">辅助管理</a>
                        <a href="{% url 'changepwd' %}" class="list-group-item">修改密码</a>
                    </div>
                </div>
        {% else %}
            <h1>你尚未登录，只能访问公开内容！</h1>
        {% endif %}
    </div>
{% endblock %}

clothes_jxc/templates/login.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock %}

{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="/login/" method="post">
                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}
                {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>
                <div class="form-group">
                    {{ login_form.username.label_tag }}
                    {{ login_form.username }}
                    {{ login_form.username.errors }}
                </div>
                <div class="form-group">
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                    {{ login_form.password.errors }}
                </div>
                <div class="form-group">
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}
                    {{ login_form.captcha.errors }}
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">登录</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

clothes_jxc/templates/register.html
{% extends 'base2.html' %}

{% block title %}注册{% endblock %}
{% block content %}
    <div class="container" style="height: 600px">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-register' action="/register/" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}

                {% csrf_token %}

                <h2 class="text-center">欢迎注册</h2>
                <div class="form-group">
                    {{ register_form.username.label_tag }}
                    {{ register_form.username }}
                    {{ register_form.username.errors }}
                    <p id="checkUsername"></p>
                </div>
                <div class="form-group">
                    {{ register_form.password1.label_tag }}
                    {{ register_form.password1 }}
                    {{ register_form.password1.errors }}
                </div>
                <div class="form-group">
                    {{ register_form.password2.label_tag }}
                    {{ register_form.password2 }}
                    {{ register_form.password2.errors }}
                </div>
                <div class="form-group">
                    {{ register_form.name.label_tag }}
                    {{ register_form.name }}
                    {{ register_form.name.errors }}
                </div>
                <div class="form-group">
                    {{ register_form.captcha.label_tag }}
                    {{ register_form.captcha }}
                    {{ register_form.captcha.errors }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">注册</button>

            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}